# Generated by Django 5.0 on 2024-01-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_volunteer_vol_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_image', models.ImageField(upload_to='slide')),
                ('slide_heading', models.CharField(max_length=100)),
                ('slide_content', models.CharField(max_length=200)),
                ('slide_is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'slides',
            },
        ),
    ]
