# Generated by Django 5.0 on 2024-01-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vol_heading', models.TextField()),
                ('vol_content', models.TextField()),
                ('vol_image', models.ImageField(upload_to='volunteer/')),
            ],
            options={
                'verbose_name_plural': 'volunteers',
            },
        ),
    ]
