# Generated by Django 5.0 on 2024-01-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='vol_image',
            field=models.ImageField(upload_to='static/images/volunteer/'),
        ),
    ]
