# Generated by Django 5.0 on 2024-01-22 07:11

import base.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_image', models.ImageField(upload_to=base.models.upload_to)),
                ('content_with_images', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
