# Generated by Django 5.0 on 2024-01-22 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_blog_create_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
